import Head from "next/head";
import { useRouter } from "next/router";
import Link from "next/link";
import styles from "../styles/details.module.css";
import NavBar from "../components/navBar";
import { useDispatch, useSelector } from "react-redux";
import { addToCart } from "../store/cartSlice";
import { useEffect, useState } from "react";

function Detail() {
  const router = useRouter();
  const [product, setProduct] = useState([]);
  const products = useSelector((state) => state.cart.products);
  const dispatch = useDispatch();
  let productItem;
  let arr = [];

  useEffect(() => {
    if (!router.isReady) return;

    productItem = products.filter((item) => {
      return item.id == router.query.id;
    });
    arr.push(productItem);
    setProduct(productItem);
  }, [router.query.id]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <section>
          <div className={styles.detailContainer}>
            {product.length !== 0
              ? product.map((item) => {
                  return (
                    <>
                      <div className={styles.imgContainer}>
                        <img
                          src={item.images[0]}
                          alt="Product Image"
                          className={styles.detailImg}
                        />
                      </div>
                      <div className={styles.productInfo}>
                        <h3 className={styles.productTitle}>{item.title}</h3>
                        <p className={styles.productDesc}>{item.description}</p>
                        <p className={styles.info}>Brand: {item.brand}</p>
                        <p className={styles.info}>Rating: {item.rating}</p>
                        <p className={styles.productPrice}>${item.price}</p>
                        {/* <p></p> */}
                        <div className={styles.quantity}></div>
                        <a
                          className={styles.btn}
                          onClick={() => dispatch(addToCart(item))}
                        >
                          🛒 Add To Cart
                        </a>
                      </div>
                    </>
                  );
                })
              : null}
          </div>
        </section>
      </main>
    </>
  );
}

export default Detail;
