import Head from "next/head";
import styles from "../styles/checkout.module.css";
import NavBar from "../components/navBar";

function Checkout() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar></NavBar>
        <section>
          <h1>My Cart</h1>
          <div className={styles.checkout}>
            <div className={styles.detailsWrapper}>
              <div className={styles.productDetails}>
                <div className={styles.imgContainer}>
                  <img
                    src="https://img.freepik.com/free-photo/pink-canvas-sneakers-with-polka-dot-unisex-footwear-fashion_53876-106039.jpg?w=2000"
                    alt="Product image"
                    className={styles.img}
                  />
                </div>
                <div className={styles.productInfo}>
                  <div className={styles.info}>
                    <p>Title</p>
                    <p>Remove</p>
                  </div>
                  <div className={styles.quantity}>
                    <p>Qty:</p>
                    <p className={styles.minus}>-</p>
                    <p>5</p>
                    <p className={styles.add}>+</p>
                  </div>
                  <div className={styles.info}>
                    <p>
                      Price: <span>$89</span>
                    </p>
                    <p>
                      SubToTal: <span>$781</span>
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div className={styles.paymentSummary}>
              <p className={styles.title}>Order Summary</p>
              <div className={styles.info}>
                <p>selected Item(s)</p>
                <p>3</p>
              </div>
              <div className={styles.info}>
                <p>Total Price</p>
                <p>$789</p>
              </div>
              <div className={styles.info}>
                <p>Discount</p>
                <p>$0</p>
              </div>
              <div className={styles.total}>
                <p>Grand Total</p>
                <p>$890</p>
              </div>
              <button href="" className={styles.paymentBtn}>
                Pay For Items
              </button>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}

export default Checkout;
