import Head from "next/head";
import Link from "next/link";
import styles from "../styles/details.module.css";
import NavBar from "../components/navBar";

function Detail() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />{" "}
        <section>
          <div className={styles.detailContainer}>
            <div className={styles.imgContainer}>
              <img
                src="https://img.freepik.com/free-photo/pink-canvas-sneakers-with-polka-dot-unisex-footwear-fashion_53876-106039.jpg?w=2000"
                alt="Product Image"
                className={styles.detailImg}
              />
            </div>
            <div className={styles.productInfo}>
              <h3 className={styles.productTitle}>Product Title</h3>
              <p className={styles.productDesc}>
                Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                Praesentium, dolorum? Labore quibusdam repudiandae at rem
                assumenda! Ratione laudantium consectetur nesciunt!
              </p>
              <p className={styles.productPrice}>$98</p>
              <div className={styles.quantity}>
                <p>Qty:</p>
                <p className={styles.minus}>-</p>
                <p>5</p>
                <p className={styles.add}>+</p>
              </div>
              <a href="" className={styles.btn}>
                Add To Cart
              </a>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}

export default Detail;
