import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import NavBar from "../components/navBar";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [data, setData] = useState();

  /*useEffect(() => {
    // return () => {
    //   second
    // }
    async function getProducts() {
      try {
        const res = await fetch("https://dummyjson.com/products");
        const { products } = await res.json();
        setData(products);
      } catch (error) {
        console.error(error);
      }
    }
    getProducts();
  }, []);
  */

  //console.log(data);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NavBar></NavBar>

        <section>
          <h1 className="header">our products</h1>
          <div className={styles.cardsContainer}>
            <div className={styles.card}>
              <div className={styles.cardImgContainer}>
                <img
                  src="https://img.freepik.com/free-photo/pink-canvas-sneakers-with-polka-dot-unisex-footwear-fashion_53876-106039.jpg?w=2000"
                  alt="card image"
                  className={styles.cardImg}
                />
              </div>
              <div className={styles.cardInfo}>
                <h3 className={styles.cardTitle}>Title</h3>
                <p className={styles.cardDesc}>
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                  Saepe, libero tempore! Sequi magni deleniti quidem.
                </p>
                <p className={styles.cardPrice}>$59</p>
                <div className={styles.btns}>
                  <Link href="id" className={styles.detailsBtn}>
                    More Details
                  </Link>
                  <a className={styles.cartBtn}>Cart</a>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
